import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';

import { StudentShell } from '@/components/student-shell';
import { studentTheme as t } from '@/constants/student-theme';
import { Avaliacao, EvolucaoResponse, obterEvolucao } from '@/services/evolucao';

const campos=[['peso_kg','Peso','kg'],['gordura_percentual','Gordura','%'],['massa_magra_kg','Massa magra','kg'],['cintura_cm','Cintura','cm'],['braco_cm','Braço','cm'],['coxa_cm','Coxa','cm']] as const;
function valor(v?:number|null,s=''){return v===null||v===undefined?'—':`${String(v).replace('.',',')}${s?` ${s}`:''}`;}
function dataBr(v:string){const [y,m,d]=v.slice(0,10).split('-');return y&&m&&d?`${d}/${m}/${y}`:v;}
function sinal(delta?:number|null){if(delta===null||delta===undefined)return '';return `${delta>0?'+':''}${String(delta).replace('.',',')}`;}

function MiniGrafico({avaliacoes,campo,unidade}:{avaliacoes:Avaliacao[];campo:keyof Avaliacao;unidade:string}){
  const pontos=avaliacoes.slice(0,8).reverse().map(a=>({data:a.data_avaliacao,v:Number(a[campo])})).filter(x=>Number.isFinite(x.v));
  if(pontos.length<2)return <Text style={s.noChart}>São necessárias pelo menos duas avaliações para formar o gráfico.</Text>;
  const max=Math.max(...pontos.map(x=>x.v)); const min=Math.min(...pontos.map(x=>x.v)); const span=Math.max(max-min,1);
  return <View style={s.chart}>{pontos.map((p,i)=>{const h=26+((p.v-min)/span)*58;return <View key={`${p.data}-${i}`} style={s.barCol}><Text style={s.barValue}>{String(p.v).replace('.',',')}</Text><View style={[s.bar,{height:h}]}/><Text style={s.barDate}>{p.data.slice(5).split('-').reverse().join('/')}</Text></View>})}<Text style={s.unit}>{unidade}</Text></View>;
}

export default function EvolucaoScreen(){
  const [dados,setDados]=useState<EvolucaoResponse|null>(null); const [carregando,setCarregando]=useState(true); const [atualizando,setAtualizando]=useState(false); const [erro,setErro]=useState('');
  const carregar=useCallback(async(refresh=false)=>{refresh?setAtualizando(true):setCarregando(true);try{setErro('');setDados(await obterEvolucao());}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar sua evolução.');}finally{setCarregando(false);setAtualizando(false);}},[]);
  useFocusEffect(useCallback(()=>{carregar();},[carregar])); const atual=dados?.avaliacoes[0]; const anterior=dados?.avaliacoes[1];
  const graficoCampo=useMemo(()=>dados?.avaliacoes.some(a=>a.peso_kg!=null)?'peso_kg':dados?.avaliacoes.some(a=>a.gordura_percentual!=null)?'gordura_percentual':null,[dados]);
  return <StudentShell><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={atualizando} onRefresh={()=>carregar(true)}/>}>
    <Text style={s.eyebrow}>EVOLUÇÃO</Text><Text style={s.title}>Sua evolução</Text><Text style={s.subtitle}>Acompanhe avaliações físicas, medidas e mudanças ao longo do tempo.</Text>
    {carregando?<ActivityIndicator color={t.orange} style={s.loader}/>:null}{erro?<View style={s.error}><Text style={s.errorText}>{erro}</Text></View>:null}
    {!carregando&&dados?.avaliacoes.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Nenhuma avaliação registrada</Text><Text style={s.emptyText}>Quando seu professor registrar sua primeira avaliação física, os dados e gráficos aparecerão aqui.</Text></View>:null}
    {atual?<><View style={s.hero}><Text style={s.heroSmall}>ÚLTIMA AVALIAÇÃO · {dataBr(atual.data_avaliacao)}</Text><View style={s.heroRow}><View><Text style={s.heroLabel}>PESO</Text><Text style={s.heroValue}>{valor(atual.peso_kg,'kg')}</Text></View><View><Text style={s.heroLabel}>GORDURA</Text><Text style={s.heroValue}>{valor(atual.gordura_percentual,'%')}</Text></View><View><Text style={s.heroLabel}>IMC</Text><Text style={s.heroValue}>{valor(atual.imc)}</Text></View></View>{atual.professor_nome?<Text style={s.prof}>Avaliado por {atual.professor_nome}</Text>:null}</View>
    <Text style={s.section}>DESDE A AVALIAÇÃO ANTERIOR</Text><View style={s.grid}>{campos.map(([campo,label,unit])=>{const c=dados?.comparacao?.[campo];const d=c?.delta;return <View style={s.metricCard} key={campo}><Text style={s.metricLabel}>{label.toUpperCase()}</Text><Text style={s.metricValue}>{valor(c?.atual,unit)}</Text><Text style={[s.delta,d!==null&&d!==undefined&&d!==0?{color:d>0?t.orange:t.success}:null]}>{anterior?`${sinal(d)} ${unit}`:'sem comparação'}</Text></View>})}</View>
    {graficoCampo?<><Text style={s.section}>PROGRESSO · {graficoCampo==='peso_kg'?'PESO':'GORDURA'}</Text><View style={s.chartCard}><MiniGrafico avaliacoes={dados!.avaliacoes} campo={graficoCampo} unidade={graficoCampo==='peso_kg'?'kg':'%'}/></View></>:null}
    <Text style={s.section}>AVALIAÇÕES</Text>{dados?.avaliacoes.map((a,i)=><View style={s.evalCard} key={a.id}><View style={s.evalIndex}><Text style={s.evalIndexText}>{dados.avaliacoes.length-i}</Text></View><View style={{flex:1}}><Text style={s.evalDate}>{dataBr(a.data_avaliacao)}</Text><Text style={s.evalMeta}>{valor(a.peso_kg,'kg')} · {valor(a.gordura_percentual,'% gordura')} · IMC {valor(a.imc)}</Text>{a.observacoes?<Text style={s.evalObs} numberOfLines={2}>{a.observacoes}</Text>:null}</View></View>)}</>:null}
  </ScrollView></StudentShell>;
}
const s=StyleSheet.create({content:{padding:14,paddingTop:22,paddingBottom:30},eyebrow:{color:t.orange,fontSize:9,fontWeight:'900',letterSpacing:1.2},title:{color:t.text,fontSize:29,fontWeight:'900',marginTop:4},subtitle:{color:t.muted,fontSize:11,lineHeight:17,marginTop:5,marginBottom:16},loader:{marginTop:40},error:{backgroundColor:'#fff0ed',borderRadius:12,padding:12,marginBottom:12},errorText:{color:t.danger,fontSize:11,fontWeight:'700'},empty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:25,alignItems:'center'},emptyTitle:{color:t.text,fontSize:14,fontWeight:'900'},emptyText:{color:t.muted,fontSize:10,lineHeight:16,textAlign:'center',marginTop:6},hero:{backgroundColor:t.dark,borderRadius:19,padding:18},heroSmall:{color:t.orange,fontSize:8,fontWeight:'900',letterSpacing:1},heroRow:{flexDirection:'row',justifyContent:'space-between',marginTop:16},heroLabel:{color:'#929292',fontSize:7,fontWeight:'900',letterSpacing:.8},heroValue:{color:'#fff',fontSize:20,fontWeight:'900',marginTop:3},prof:{color:'#aaa',fontSize:8,marginTop:14},section:{color:t.muted,fontSize:8,fontWeight:'900',letterSpacing:1.1,marginTop:18,marginBottom:8},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},metricCard:{width:'48.8%',backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:16,padding:13},metricLabel:{color:t.muted,fontSize:7,fontWeight:'900',letterSpacing:.7},metricValue:{color:t.text,fontSize:17,fontWeight:'900',marginTop:5},delta:{color:t.muted,fontSize:8,fontWeight:'800',marginTop:4},chartCard:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:14},chart:{height:132,flexDirection:'row',alignItems:'flex-end',gap:7,position:'relative',paddingTop:13},barCol:{flex:1,alignItems:'center',justifyContent:'flex-end'},bar:{width:'72%',minWidth:10,maxWidth:28,backgroundColor:t.orange,borderTopLeftRadius:5,borderTopRightRadius:5},barValue:{color:t.text,fontSize:7,fontWeight:'800',marginBottom:3},barDate:{color:t.muted,fontSize:6,fontWeight:'700',marginTop:4},unit:{position:'absolute',right:0,top:0,color:t.muted,fontSize:7,fontWeight:'800'},noChart:{color:t.muted,fontSize:9,lineHeight:14,textAlign:'center',paddingVertical:22},evalCard:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:16,padding:13,marginBottom:8,flexDirection:'row',gap:11},evalIndex:{width:31,height:31,borderRadius:10,backgroundColor:'#f3eee9',alignItems:'center',justifyContent:'center'},evalIndexText:{color:t.orange,fontSize:10,fontWeight:'900'},evalDate:{color:t.text,fontSize:12,fontWeight:'900'},evalMeta:{color:t.muted,fontSize:8,marginTop:4},evalObs:{color:t.muted,fontSize:8,lineHeight:13,marginTop:6}});
