import { useCallback, useState } from 'react';
import { ActivityIndicator, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';

import { StudentShell } from '@/components/student-shell';
import { studentTheme as t } from '@/constants/student-theme';
import { Cobranca, FinanceiroResponse, gerarPix, obterFinanceiro } from '@/services/financeiro';

function dinheiro(v?: number | null) { return ((v || 0) / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function dataBr(v?: string | null) { if (!v) return '—'; const [a,m,d]=v.slice(0,10).split('-'); return a&&m&&d?`${d}/${m}/${a}`:v; }
function status(v?: string | null) { return (v || 'NÃO INFORMADO').replaceAll('_',' '); }
function corStatus(v?: string | null) { return v === 'EM_DIA' || v === 'RECEBIDO' || v === 'CONFIRMADO' ? t.success : v === 'VENCIDO' ? t.danger : t.orange; }

export default function FinanceiroScreen() {
  const [dados,setDados]=useState<FinanceiroResponse|null>(null); const [carregando,setCarregando]=useState(true);
  const [atualizando,setAtualizando]=useState(false); const [gerando,setGerando]=useState(false); const [erro,setErro]=useState('');
  const carregar=useCallback(async(refresh=false)=>{refresh?setAtualizando(true):setCarregando(true);try{setErro('');setDados(await obterFinanceiro());}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar o financeiro.');}finally{setCarregando(false);setAtualizando(false);}},[]);
  useFocusEffect(useCallback(()=>{carregar();},[carregar]));
  async function criarPix(){setGerando(true);try{setErro('');await gerarPix();await carregar(true);}catch(e){setErro(e instanceof Error?e.message:'Não foi possível gerar o PIX.');}finally{setGerando(false);}}
  const aberta=dados?.cobranca_aberta;
  return <StudentShell><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={atualizando} onRefresh={()=>carregar(true)}/>}>
    <Text style={s.eyebrow}>FINANCEIRO</Text><Text style={s.title}>Sua mensalidade</Text><Text style={s.subtitle}>Acompanhe vencimentos, cobranças e pague por PIX.</Text>
    {carregando?<ActivityIndicator style={{marginTop:30}} color={t.orange}/>:null}{erro?<View style={s.error}><Text style={s.errorText}>{erro}</Text></View>:null}
    {dados?<><View style={s.hero}><View><Text style={s.heroLabel}>SITUAÇÃO ATUAL</Text><Text style={[s.heroStatus,{color:corStatus(dados.status_financeiro_efetivo)}]}>{status(dados.status_financeiro_efetivo)}</Text><Text style={s.heroHint}>Vencimento {dataBr(dados.data_vencimento)}</Text></View><View style={s.valueBox}><Text style={s.valueLabel}>MENSALIDADE</Text><Text style={s.value}>{dinheiro(dados.plano?.valor_centavos)}</Text></View></View>
    <View style={s.info}><Row label="Plano" value={dados.plano?.nome||'—'}/><Row label="Vencimento" value={dataBr(dados.data_vencimento)}/><Row label="Tolerância" value={`${dados.tolerancia_dias} dia(s)`} last/></View>
    {aberta?<PixCard cobranca={aberta}/>:<View style={s.pixEmpty}><Text style={s.cardEyebrow}>PAGAMENTO VIA PIX</Text><Text style={s.cardTitle}>Gerar cobrança</Text><Text style={s.cardText}>{dados.asaas_configurado?'Gere o PIX da mensalidade atual. Se já existir uma cobrança, o sistema reutiliza a mesma.':'PIX temporariamente indisponível. Procure a recepção.'}</Text><Pressable style={[s.button,(!dados.asaas_configurado||gerando)&&s.buttonDisabled]} disabled={!dados.asaas_configurado||gerando} onPress={criarPix}><Text style={s.buttonText}>{gerando?'Gerando...':'Gerar PIX'}</Text></Pressable></View>}
    <Text style={s.section}>HISTÓRICO DE COBRANÇAS</Text>{dados.cobrancas.length===0?<View style={s.empty}><Text style={s.emptyText}>Nenhuma cobrança registrada.</Text></View>:dados.cobrancas.map(c=><View key={c.id} style={s.charge}><View style={{flex:1}}><Text style={s.chargeDate}>VENC. {dataBr(c.vencimento)}</Text><Text style={s.chargeValue}>{dinheiro(c.valor_centavos)}</Text>{c.data_pagamento?<Text style={s.paid}>Pago em {dataBr(c.data_pagamento)}</Text>:null}</View><View style={[s.badge,{borderColor:corStatus(c.status)}]}><Text style={[s.badgeText,{color:corStatus(c.status)}]}>{status(c.status)}</Text></View></View>)}</>:null}
  </ScrollView></StudentShell>;
}
function PixCard({cobranca}:{cobranca:Cobranca}){const uri=cobranca.pix_qr_base64?`data:image/png;base64,${cobranca.pix_qr_base64}`:null;return <View style={s.pix}><Text style={s.cardEyebrow}>PIX DA MENSALIDADE</Text><Text style={s.cardTitle}>{dinheiro(cobranca.valor_centavos)}</Text><Text style={s.cardText}>Vencimento {dataBr(cobranca.vencimento)} · {status(cobranca.status)}</Text>{uri?<Image source={{uri}} style={s.qr}/>:null}{cobranca.pix_payload?<><Text style={s.copyLabel}>PIX COPIA E COLA</Text><Text selectable style={s.copy}>{cobranca.pix_payload}</Text><Text style={s.selectHint}>Toque e segure o código para copiar.</Text></>:<Text style={s.cardText}>QR Code ainda não disponível. Atualize a tela em alguns instantes.</Text>}</View>}
function Row({label,value,last=false}:{label:string;value:string;last?:boolean}){return <View style={[s.row,last&&{borderBottomWidth:0}]}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>}
const s=StyleSheet.create({content:{padding:14,paddingTop:22,paddingBottom:32},eyebrow:{color:t.orange,fontSize:9,fontWeight:'900',letterSpacing:1.2},title:{color:t.text,fontSize:29,fontWeight:'900',marginTop:4},subtitle:{color:t.muted,fontSize:11,lineHeight:17,marginTop:5,marginBottom:16},error:{backgroundColor:'#fff0ed',borderRadius:12,padding:12,marginBottom:12},errorText:{color:t.danger,fontSize:11,fontWeight:'700'},hero:{backgroundColor:t.dark,borderRadius:18,padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},heroLabel:{color:'#888',fontSize:8,fontWeight:'900',letterSpacing:1},heroStatus:{fontSize:20,fontWeight:'900',marginTop:5},heroHint:{color:'#aaa',fontSize:9,marginTop:5},valueBox:{alignItems:'flex-end'},valueLabel:{color:'#888',fontSize:7,fontWeight:'900'},value:{color:'#fff',fontSize:18,fontWeight:'900',marginTop:5},info:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,paddingHorizontal:16,marginTop:10},row:{minHeight:47,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:t.line},rowLabel:{color:t.muted,fontSize:10},rowValue:{color:t.text,fontSize:10,fontWeight:'900'},pixEmpty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:17,marginTop:10},pix:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:17,marginTop:10,alignItems:'center'},cardEyebrow:{alignSelf:'flex-start',color:t.orange,fontSize:8,fontWeight:'900',letterSpacing:1},cardTitle:{alignSelf:'flex-start',color:t.text,fontSize:18,fontWeight:'900',marginTop:5},cardText:{alignSelf:'flex-start',color:t.muted,fontSize:10,lineHeight:16,marginTop:5},button:{backgroundColor:t.orange,borderRadius:12,minHeight:45,alignItems:'center',justifyContent:'center',marginTop:14},buttonDisabled:{opacity:.45},buttonText:{color:'#fff',fontSize:11,fontWeight:'900'},qr:{width:190,height:190,marginVertical:15},copyLabel:{alignSelf:'flex-start',color:t.muted,fontSize:8,fontWeight:'900',marginTop:4},copy:{alignSelf:'stretch',color:t.text,fontSize:9,lineHeight:14,backgroundColor:t.background,borderRadius:10,padding:11,marginTop:6},selectHint:{alignSelf:'flex-start',color:t.muted,fontSize:8,marginTop:5},section:{color:t.muted,fontSize:8,fontWeight:'900',letterSpacing:1.1,marginTop:18,marginBottom:8},empty:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:16,padding:18},emptyText:{color:t.muted,fontSize:10,textAlign:'center'},charge:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:16,padding:14,marginBottom:8,flexDirection:'row',alignItems:'center'},chargeDate:{color:t.muted,fontSize:8,fontWeight:'800'},chargeValue:{color:t.text,fontSize:15,fontWeight:'900',marginTop:4},paid:{color:t.success,fontSize:8,marginTop:3},badge:{borderWidth:1,borderRadius:20,paddingHorizontal:9,paddingVertical:5},badgeText:{fontSize:7,fontWeight:'900'}});
