import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';

import { StudentShell } from '@/components/student-shell';
import { studentTheme as t } from '@/constants/student-theme';
import { obterPreferencias, salvarPreferencias } from '@/services/experiencia';
import { sincronizarLembreteTreinoLocal } from '@/services/lembretes';

const HORARIOS = ['18:00','19:00','20:00','21:00'];

export default function PreferenciasScreen(){
  const [meta,setMeta]=useState(4); const [ativo,setAtivo]=useState(false); const [hora,setHora]=useState('19:00');
  const [carregando,setCarregando]=useState(true); const [salvando,setSalvando]=useState(false); const [msg,setMsg]=useState('');
  const carregar=useCallback(async()=>{try{const r=await obterPreferencias();setMeta(Number(r.preferencias.meta_semanal)||4);setAtivo(Boolean(r.preferencias.lembrete_treino_ativo));setHora(r.preferencias.lembrete_treino_hora||'19:00');}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível carregar.')}finally{setCarregando(false)}},[]);
  useFocusEffect(useCallback(()=>{setCarregando(true);carregar()},[carregar]));
  async function salvar(){try{setSalvando(true);setMsg('');const r=await salvarPreferencias({meta_semanal:meta,lembrete_treino_ativo:ativo,lembrete_treino_hora:hora});await sincronizarLembreteTreinoLocal(Boolean(r.preferencias.lembrete_treino_ativo),r.preferencias.lembrete_treino_hora);setMsg('Preferências salvas.');}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSalvando(false)}}
  return <StudentShell><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Perfil</Text></Pressable><Text style={s.eyebrow}>EXPERIÊNCIA</Text><Text style={s.title}>Preferências</Text><Text style={s.subtitle}>Ajuste sua meta semanal e os lembretes locais de treino.</Text>
    {carregando?<ActivityIndicator color={t.orange} style={{marginTop:30}}/>:<>
      <View style={s.card}><Text style={s.cardTitle}>Meta semanal</Text><Text style={s.cardText}>Quantos treinos você quer concluir por semana?</Text><View style={s.counter}><Pressable style={s.counterBtn} onPress={()=>setMeta(v=>Math.max(1,v-1))}><Text style={s.counterBtnText}>−</Text></Pressable><View><Text style={s.metaValue}>{meta}</Text><Text style={s.metaLabel}>treinos</Text></View><Pressable style={s.counterBtn} onPress={()=>setMeta(v=>Math.min(14,v+1))}><Text style={s.counterBtnText}>+</Text></Pressable></View></View>
      <View style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.cardTitle}>Lembrete de treino</Text><Text style={s.cardText}>Notificação local diária, sem depender do Apple Developer.</Text></View><Pressable style={[s.toggle,ativo&&s.toggleOn]} onPress={()=>setAtivo(v=>!v)}><View style={[s.knob,ativo&&s.knobOn]}/></Pressable></View>{ativo?<><Text style={s.small}>HORÁRIO</Text><View style={s.hours}>{HORARIOS.map(h=><Pressable key={h} style={[s.hour,hora===h&&s.hourActive]} onPress={()=>setHora(h)}><Text style={[s.hourText,hora===h&&s.hourTextActive]}>{h}</Text></Pressable>)}</View></>:null}</View>
      {msg?<Text style={[s.msg,msg.includes('salvas')&&s.ok]}>{msg}</Text>:null}<Pressable style={s.save} onPress={salvar} disabled={salvando}><Text style={s.saveText}>{salvando?'Salvando...':'Salvar preferências'}</Text></Pressable>
    </>}
  </ScrollView></StudentShell>
}
const s=StyleSheet.create({content:{padding:14,paddingTop:20,paddingBottom:30},back:{color:t.muted,fontSize:10,fontWeight:'800',marginBottom:16},eyebrow:{color:t.orange,fontSize:9,fontWeight:'900',letterSpacing:1.1},title:{color:t.text,fontSize:28,fontWeight:'900',marginTop:4},subtitle:{color:t.muted,fontSize:10,lineHeight:16,marginTop:6,marginBottom:16},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:16,marginBottom:11},cardTitle:{color:t.text,fontSize:16,fontWeight:'900'},cardText:{color:t.muted,fontSize:9,lineHeight:14,marginTop:4},counter:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:18},counterBtn:{width:48,height:48,borderRadius:14,backgroundColor:'#f2eee9',alignItems:'center',justifyContent:'center'},counterBtnText:{color:t.text,fontSize:26,fontWeight:'800'},metaValue:{color:t.orange,fontSize:32,fontWeight:'900',textAlign:'center'},metaLabel:{color:t.muted,fontSize:8,fontWeight:'800',textAlign:'center'},row:{flexDirection:'row',alignItems:'center',gap:12},toggle:{width:48,height:28,borderRadius:15,backgroundColor:'#ddd8d2',padding:3},toggleOn:{backgroundColor:t.orange},knob:{width:22,height:22,borderRadius:11,backgroundColor:'#fff'},knobOn:{transform:[{translateX:20}]},small:{color:t.muted,fontSize:8,fontWeight:'900',letterSpacing:.9,marginTop:18},hours:{flexDirection:'row',gap:7,marginTop:8},hour:{flex:1,paddingVertical:11,borderRadius:10,backgroundColor:'#f4f1ed',alignItems:'center'},hourActive:{backgroundColor:t.dark},hourText:{color:t.text,fontSize:10,fontWeight:'800'},hourTextActive:{color:'#fff'},msg:{color:t.danger,fontSize:10,textAlign:'center',marginVertical:8},ok:{color:t.success},save:{backgroundColor:t.orange,minHeight:48,borderRadius:13,alignItems:'center',justifyContent:'center',marginTop:4},saveText:{color:'#fff',fontSize:11,fontWeight:'900'}});
