import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Href, router, useLocalSearchParams } from 'expo-router';

import { studentTheme as t } from '@/constants/student-theme';
import { obterResumoTreino, ResumoTreino, salvarFeedbackTreino } from '@/services/experiencia';

const EMOJIS=['😫','😕','🙂','💪','🔥'];
const LABELS=['Muito pesado','Pesado','Bom','Forte','Excelente'];
const duracao=(s:number)=>s>=3600?`${Math.floor(s/3600)}h ${Math.round((s%3600)/60)}min`:`${Math.max(1,Math.round(s/60))} min`;

export default function ResumoScreen(){
 const {id}=useLocalSearchParams<{id:string}>(); const sid=Number(id); const [dados,setDados]=useState<ResumoTreino|null>(null); const [nota,setNota]=useState(0); const [comentario,setComentario]=useState(''); const [erro,setErro]=useState(''); const [salvando,setSalvando]=useState(false);
 useEffect(()=>{(async()=>{try{const r=await obterResumoTreino(sid);setDados(r.resumo);setNota(Number(r.resumo.percepcao_esforco)||0);setComentario(r.resumo.feedback_mobile||'')}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar o resumo.')}})()},[sid]);
 async function salvar(){if(!nota){setErro('Escolha como foi o treino.');return}try{setSalvando(true);setErro('');const r=await salvarFeedbackTreino(sid,nota,comentario);setDados(r.resumo);router.replace('/home' as Href)}catch(e){setErro(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSalvando(false)}}
 if(!dados)return <SafeAreaView style={s.loading}><ActivityIndicator color={t.orange}/><Text style={s.loadingText}>{erro||'Preparando seu resumo...'}</Text></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>TREINO CONCLUÍDO</Text><Text style={s.title}>Mandou bem! 🎉</Text><Text style={s.subtitle}>{dados.treino_nome} · {dados.ficha_nome}</Text><View style={s.hero}><View><Text style={s.heroLabel}>DURAÇÃO</Text><Text style={s.heroValue}>{duracao(dados.duracao_segundos)}</Text></View><View><Text style={s.heroLabel}>EXERCÍCIOS</Text><Text style={s.heroValue}>{dados.exercicios_concluidos}</Text></View><View><Text style={s.heroLabel}>VOLUME</Text><Text style={s.heroValue}>{dados.volume_kg.toLocaleString('pt-BR')} kg</Text></View></View><View style={s.card}><Text style={s.cardTitle}>Como foi o treino?</Text><Text style={s.cardText}>Esse feedback ajuda a acompanhar sua percepção de esforço.</Text><View style={s.emojis}>{EMOJIS.map((e,i)=><Pressable key={e} style={[s.emoji,nota===i+1&&s.emojiActive]} onPress={()=>setNota(i+1)}><Text style={s.emojiText}>{e}</Text></Pressable>)}</View><Text style={s.label}>{nota?LABELS[nota-1]:'Selecione uma opção'}</Text><TextInput multiline style={s.input} value={comentario} onChangeText={setComentario} placeholder="Quer registrar algo sobre o treino?" placeholderTextColor="#999"/></View>{erro?<Text style={s.error}>{erro}</Text>:null}<Pressable style={s.save} onPress={salvar} disabled={salvando}><Text style={s.saveText}>{salvando?'Salvando...':'Salvar e voltar ao início'}</Text></Pressable><Pressable onPress={()=>router.replace('/home' as Href)}><Text style={s.skip}>Pular feedback</Text></Pressable></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:t.background},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:t.background,gap:10},loadingText:{color:t.muted,fontSize:10},content:{padding:18,paddingTop:34,paddingBottom:30},eyebrow:{color:t.orange,fontSize:9,fontWeight:'900',letterSpacing:1.1},title:{color:t.text,fontSize:31,fontWeight:'900',marginTop:5},subtitle:{color:t.muted,fontSize:10,marginTop:6,marginBottom:18},hero:{backgroundColor:t.dark,borderRadius:19,padding:17,flexDirection:'row',justifyContent:'space-between',marginBottom:12},heroLabel:{color:'#999',fontSize:7,fontWeight:'900'},heroValue:{color:'#fff',fontSize:16,fontWeight:'900',marginTop:5},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:19,padding:17},cardTitle:{color:t.text,fontSize:18,fontWeight:'900'},cardText:{color:t.muted,fontSize:9,lineHeight:14,marginTop:4},emojis:{flexDirection:'row',justifyContent:'space-between',marginTop:18},emoji:{width:50,height:50,borderRadius:16,backgroundColor:'#f2eee9',alignItems:'center',justifyContent:'center'},emojiActive:{borderWidth:2,borderColor:t.orange,backgroundColor:'#fff7f2'},emojiText:{fontSize:24},label:{color:t.text,fontSize:10,fontWeight:'900',textAlign:'center',marginTop:9},input:{minHeight:82,borderWidth:1,borderColor:t.line,borderRadius:12,padding:11,color:t.text,fontSize:10,textAlignVertical:'top',marginTop:14},error:{color:t.danger,fontSize:10,fontWeight:'700',textAlign:'center',marginTop:10},save:{backgroundColor:t.orange,minHeight:49,borderRadius:13,alignItems:'center',justifyContent:'center',marginTop:13},saveText:{color:'#fff',fontSize:11,fontWeight:'900'},skip:{color:t.muted,fontSize:10,fontWeight:'800',textAlign:'center',padding:16}});
