import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';

import { studentTheme as t } from '@/constants/student-theme';
import { obterTreinoHistorico, SessaoHistoricoDetalhe } from '@/services/historico';

function dataBr(valor?: string | null) { if (!valor) return '—'; const d=new Date(valor.replace(' ','T')); return Number.isNaN(d.getTime())?valor.slice(0,10):d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}); }
function duracao(seg?: number | null){const m=Math.max(0,Math.round(Number(seg||0)/60));return m<60?`${m} min`:`${Math.floor(m/60)}h ${m%60}min`;}

export default function HistoricoDetalheScreen(){
  const { id }=useLocalSearchParams<{id:string}>(); const [sessao,setSessao]=useState<SessaoHistoricoDetalhe|null>(null); const [erro,setErro]=useState('');
  const carregar=useCallback(async()=>{try{setErro('');const r=await obterTreinoHistorico(Number(id));setSessao(r.sessao);}catch(e){setErro(e instanceof Error?e.message:'Não foi possível abrir este treino.');}},[id]);
  useFocusEffect(useCallback(()=>{carregar();},[carregar]));
  return <View style={s.page}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View style={{flex:1}}><Text style={s.headerSmall}>TREINO CONCLUÍDO</Text><Text style={s.headerTitle}>{sessao?.treino_nome||'Histórico'}</Text></View></View><ScrollView contentContainerStyle={s.content}>
    {!sessao&&!erro?<ActivityIndicator color={t.orange} style={{marginTop:50}}/>:null}{erro?<View style={s.error}><Text style={s.errorText}>{erro}</Text></View>:null}
    {sessao?<><View style={s.summary}><View><Text style={s.sumLabel}>DATA</Text><Text style={s.sumValue}>{dataBr(sessao.finalizado_em||sessao.iniciado_em)}</Text></View><View><Text style={s.sumLabel}>DURAÇÃO</Text><Text style={s.sumValue}>{duracao(sessao.duracao_segundos)}</Text></View><View><Text style={s.sumLabel}>EXERCÍCIOS</Text><Text style={s.sumValue}>{sessao.exercicios_concluidos}/{sessao.total_exercicios}</Text></View></View>
    <Text style={s.section}>EXERCÍCIOS</Text>{sessao.itens.map((item,i)=><View style={s.card} key={item.id}><View style={s.number}><Text style={s.numberText}>{i+1}</Text></View><View style={{flex:1}}><Text style={s.name}>{item.exercicio_nome}</Text>{item.grupo_muscular?<Text style={s.group}>{item.grupo_muscular}</Text>:null}<View style={s.metrics}><View><Text style={s.metricLabel}>SÉRIES</Text><Text style={s.metricValue}>{item.series_realizadas??'—'}</Text></View><View><Text style={s.metricLabel}>REPS</Text><Text style={s.metricValue}>{item.repeticoes_realizadas||'—'}</Text></View><View><Text style={s.metricLabel}>CARGA</Text><Text style={s.metricValue}>{item.carga_realizada||'—'}</Text></View></View>{item.observacoes_execucao?<Text style={s.note}>{item.observacoes_execucao}</Text>:null}</View></View>)}
    {sessao.observacoes?<View style={s.obs}><Text style={s.obsTitle}>OBSERVAÇÃO FINAL</Text><Text style={s.obsText}>{sessao.observacoes}</Text></View>:null}</>:null}
  </ScrollView></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:t.background},header:{paddingTop:54,paddingHorizontal:14,paddingBottom:15,backgroundColor:t.dark,flexDirection:'row',alignItems:'center',gap:10},back:{width:38,height:38,borderRadius:19,backgroundColor:'#292929',alignItems:'center',justifyContent:'center'},backText:{color:'#fff',fontSize:30,lineHeight:32,marginTop:-3},headerSmall:{color:t.orange,fontSize:8,fontWeight:'900',letterSpacing:1},headerTitle:{color:'#fff',fontSize:19,fontWeight:'900',marginTop:2},content:{padding:14,paddingBottom:35},error:{backgroundColor:'#fff0ed',borderRadius:12,padding:12},errorText:{color:t.danger,fontSize:11,fontWeight:'700'},summary:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:18,padding:16,flexDirection:'row',justifyContent:'space-between'},sumLabel:{color:t.muted,fontSize:7,fontWeight:'900',letterSpacing:.8},sumValue:{color:t.text,fontSize:11,fontWeight:'900',marginTop:4},section:{color:t.muted,fontSize:8,fontWeight:'900',letterSpacing:1.1,marginTop:18,marginBottom:8},card:{backgroundColor:t.card,borderWidth:1,borderColor:t.line,borderRadius:17,padding:14,marginBottom:9,flexDirection:'row',gap:11},number:{width:29,height:29,borderRadius:9,backgroundColor:'#f3eee9',alignItems:'center',justifyContent:'center'},numberText:{color:t.orange,fontSize:10,fontWeight:'900'},name:{color:t.text,fontSize:13,fontWeight:'900'},group:{color:t.muted,fontSize:8,marginTop:2},metrics:{flexDirection:'row',gap:28,marginTop:12},metricLabel:{color:t.muted,fontSize:7,fontWeight:'800'},metricValue:{color:t.text,fontSize:11,fontWeight:'900',marginTop:2},note:{color:t.muted,fontSize:9,lineHeight:14,marginTop:10,borderTopWidth:1,borderTopColor:t.line,paddingTop:9},obs:{backgroundColor:t.dark,borderRadius:17,padding:15,marginTop:4},obsTitle:{color:t.orange,fontSize:8,fontWeight:'900',letterSpacing:1},obsText:{color:'#ddd',fontSize:10,lineHeight:16,marginTop:7}});
